from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('service/<slug:service_key>/', views.service_page, name='service-page'),
    path('api/acm/', views.acm, name='acm'),
    path('api/apigateway/', views.apigateway, name='apigateway'),
    path('api/appconfig/', views.appconfig, name='appconfig'),
    path('api/athena/', views.athena, name='athena'),
    path('api/autoscaling/', views.autoscaling, name='autoscaling'),
    path('api/backup/', views.backup, name='backup'),
    path('api/bedrockruntime/', views.bedrockruntime, name='bedrockruntime'),
    path('api/codebuild/', views.codebuild, name='codebuild'),
    path('api/codedeploy/', views.codedeploy, name='codedeploy'),
    path('api/cloudformation/', views.cloudformation, name='cloudformation'),
    path('api/cognito/', views.cognito, name='cognito'),
    path('api/cloudwatch/', views.cloudwatch, name='cloudwatch'),
    path('api/dynamodb/', views.dynamodb, name='dynamodb'),
    path('api/eventbridge/', views.eventbridge, name='eventbridge'),
    path('api/health/', views.health, name='health'),
    path('api/glue/', views.glue, name='glue'),
    path('api/ec2/', views.ec2, name='ec2'),
    path('api/ecr/', views.ecr, name='ecr'),
    path('api/ecs/', views.ecs, name='ecs'),
    path('api/eks/', views.eks, name='eks'),
    path('api/elasticache/', views.elasticache, name='elasticache'),
    path('api/elasticloadbalancing/', views.elasticloadbalancing, name='elasticloadbalancing'),
    path('api/identity/', views.identity, name='identity'),
    path('api/firehose/', views.firehose, name='firehose'),
    path('api/iam/', views.iam, name='iam'),
    path('api/kafka/', views.kafka, name='kafka'),
    path('api/kinesis/', views.kinesis, name='kinesis'),
    path('api/kms/', views.kms, name='kms'),
    path('api/lambda/', views.lambda_, name='lambda'),
    path('api/opensearch/', views.opensearch, name='opensearch'),
    path('api/pipes/', views.pipes, name='pipes'),
    path('api/resourcegroupstagging/', views.resourcegroupstagging, name='resourcegroupstagging'),
    path('api/rds/', views.rds, name='rds'),
    path('api/route53/', views.route53, name='route53'),
    path('api/s3/', views.s3, name='s3'),
    path('api/scheduler/', views.scheduler, name='scheduler'),
    path('api/secretsmanager/', views.secretsmanager, name='secretsmanager'),
    path('api/ses/', views.ses, name='ses'),
    path('api/sns/', views.sns, name='sns'),
    path('api/sqs/', views.sqs, name='sqs'),
    path('api/ssm/', views.ssm, name='ssm'),
    path('api/stepfunctions/', views.stepfunctions, name='stepfunctions'),
    path('api/transfer/', views.transfer, name='transfer'),
    path('api/resources/', views.resources, name='resources'),
]
