"""S3 lab definitions."""

from __future__ import annotations

from .monolith import (
    S3_BUCKET_SECURITY_LAB,
    S3_CORS_LAB,
    S3_CREATE_BUCKET_LAB,
    S3_DEFAULT_ENCRYPTION_LAB,
    S3_LIFECYCLE_RETENTION_LAB,
    S3_METADATA_TAGS_LAB,
    S3_MULTIPART_UPLOAD_LAB,
    S3_OBJECT_NOTIFICATIONS_LAB,
    S3_OBJECT_WORKFLOW_LAB,
    S3_PREFIX_COPY_LAB,
    S3_PRESIGNED_URL_LAB,
    S3_VERSION_RECOVERY_LAB,
)

LABS = [
    S3_CREATE_BUCKET_LAB,
    S3_OBJECT_WORKFLOW_LAB,
    S3_PREFIX_COPY_LAB,
    S3_METADATA_TAGS_LAB,
    S3_VERSION_RECOVERY_LAB,
    S3_PRESIGNED_URL_LAB,
    S3_BUCKET_SECURITY_LAB,
    S3_DEFAULT_ENCRYPTION_LAB,
    S3_LIFECYCLE_RETENTION_LAB,
    S3_CORS_LAB,
    S3_OBJECT_NOTIFICATIONS_LAB,
    S3_MULTIPART_UPLOAD_LAB,
]
