"""SQS lab definitions."""

from __future__ import annotations

from .monolith import (
    SQS_BATCH_MESSAGES_LAB,
    SQS_CREATE_QUEUE_LAB,
    SQS_DEAD_LETTER_REDRIVE_LAB,
    SQS_DELAYED_MESSAGE_LAB,
    SQS_FIFO_ORDERING_LAB,
    SQS_MESSAGE_LIFECYCLE_LAB,
    SQS_PURGE_DELETE_LAB,
    SQS_QUEUE_CONFIGURATION_LAB,
    SQS_VISIBILITY_TIMEOUT_LAB,
)

LABS = [
    SQS_CREATE_QUEUE_LAB,
    SQS_MESSAGE_LIFECYCLE_LAB,
    SQS_VISIBILITY_TIMEOUT_LAB,
    SQS_DELAYED_MESSAGE_LAB,
    SQS_BATCH_MESSAGES_LAB,
    SQS_QUEUE_CONFIGURATION_LAB,
    SQS_DEAD_LETTER_REDRIVE_LAB,
    SQS_FIFO_ORDERING_LAB,
    SQS_PURGE_DELETE_LAB,
]
